todo/urls.py
from django.contrib import admin
from django.urls import path
from todo.views import (
    IndexView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    condition = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "content",
            "deadline",
            "tags",
        ]

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False
    )
    deadline = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )

todo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from todo.forms import TaskForm
from todo.models import Task, Tag


class IndexView(View):
    template_name = "todo/index.html"

    def get(self, request, *args, **kwargs):
        task_list = Task.objects.all().order_by("condition", "-created")
        context = {"task_list": task_list}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        task_id = request.POST.get("task_id")
        if task_id:
            task = Task.objects.get(pk=task_id)
            task.condition = not task.condition
            task.save()
        return redirect("todo:index")


class TagListView(View):
    template_name = "todo/tag_list.html"

    def get(self, request, *args, **kwargs):
        tag_list = Tag.objects.all()
        context = {"tag_list": tag_list}
        return render(request, self.template_name, context)


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>TODO list
  </h1>
  <a class="btn btn-primary link-to-page" href="{% url 'todo:task-create' %}">
    Create task
  </a>
  <p>Welcome to your Todo list.</p>

  <table class="table">

    {% for task in task_list %}
      <tr>
        <td>
          <h3>
            {{ task.content }}
            {% if task.condition %}<span style="color: green;">[Done]</span>{% else %}
              <span style="color: red;">[Not Done]</span>{% endif %}
          </h3>

          <p>Created: {{ task.datetime }}</p>
          <p>Tags: {% for tag in task.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
            <a class="btn btn-outline-primary" href="{% url 'todo:task-update' pk=task.id %}">Update Task</a>
            <a class="btn btn-outline-danger" href="{% url 'todo:task-delete' pk=task.id %}">Delete Task</a></p>
        </td>
        <td>
          <form method="post" action="{% url 'todo:index' %}">
            {% csrf_token %}
            <input type="hidden" name="task_id" value="{{ task.id }}">
            {% if task.condition %}
              <button class="btn btn-secondary" type="submit" name="action" value="undo">Undo ⎌</button>
            {% else %}
              <button class="btn btn-success" type="submit" name="action" value="complete">Task Complete!</button>
            {% endif %}
          </form>
        </td>
      </tr>
    {% endfor %}
  </table>

{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag.</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags list
  </h1>
  <a class="btn btn-primary" href="{% url 'todo:tag-create' %}">
    Create tag
  </a>
  <p>Welcome to tag list</p>

  <table class="table">
    <tr>
      <th>Tag</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for tag in tag_list %}
      <tr>
        <td>
          {{ tag.name }}
        </td>
        <td>
          <a class="btn btn-primary" href="{% url 'todo:tag-update' pk=tag.id %}">Update</a>
        </td>
        <td>
          <a class="btn btn-danger" href="{% url 'todo:tag-delete' pk=tag.id %}">Delete</a>
        </td>
      </tr>

    {% endfor %}
  </table>

{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task.</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}